/*
 * PriceTable.java
 *
 * Created on otrdiena, 2007, 17 aprîlis, 09:39
 */

package ui;

import bikdesigner.HibernateUtil;
import data.PriceList;
import javax.swing.RowSorter;
import javax.swing.table.TableRowSorter;
import org.hibernate.Session;

/**
 *
 * @author  mpurins
 */
public class PriceTable extends javax.swing.JPanel {
    
    private PriceList priceList = new PriceList(HibernateUtil.getCurrentSession());
    private RowSorter rs = new TableRowSorter(priceList);
    private Integer selectedId = 0;
    private Session hibernateSession;
    
    /** Creates new form PriceTable */
    public PriceTable() {
        initComponents();

        table.setModel(priceList);
        table.setRowSorter(rs);
        table.getColumnModel().getColumn(0).setPreferredWidth(40);
        table.getColumnModel().getColumn(0).setMaxWidth(40);
        table.getColumnModel().getColumn(1).setPreferredWidth(40);
        table.getColumnModel().getColumn(2).setPreferredWidth(190);
        table.getColumnModel().getColumn(3).setPreferredWidth(40);
        table.getColumnModel().getColumn(4).setMaxWidth(30);
        table.getColumnModel().getColumn(4).setPreferredWidth(30);
        table.getColumnModel().getColumn(5).setMaxWidth(70);
        table.getColumnModel().getColumn(5).setPreferredWidth(70);

    }
    
    public void refreshData() {
        getPriceList().refreshData();
    }

    public PriceList getPriceList() {
        return priceList;
    }

    public void setPriceList(PriceList priceList) {
        this.priceList = priceList;
    }

    public Integer getSelectedId() {
        return new Integer( (Integer) table.getValueAt(table.getSelectedRow(),0));
    }

    public void setSelectedId(Integer selectedId) {
        this.selectedId = selectedId;
    }

    public Session getHibernateSession() {
        return hibernateSession;
    }

    public void setHibernateSession(Session hibernateSession) {
        this.hibernateSession = hibernateSession;
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        tableScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        table.setModel(getPriceList());
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });

        tableScrollPane.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
        if (evt.getClickCount()==2) {
            this.firePropertyChange("selectionConfirmed", false, true);
        }
    }//GEN-LAST:event_tableMouseClicked
    public void setFilter(String filterVal){
        this.priceList.setFilter(filterVal.trim());
        table.validate();

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
